version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=whiteboard
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
volumes:
  postgres-data: